### Trying to convert a simple model

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

# load iris dataset and set features / target.
iris = datasets.load_iris()
indices = np.random.permutation(len(iris.data))
iris_X = iris.data[indices[:-10]]
iris_y = iris.target[indices[:-10]]

print("Data For Testing:")
print(iris.data[indices[-10:]])
print(iris.target[indices[-10:]])

# Create and fit a model
model = LogisticRegression()
model.fit(iris_X, iris_y)
cross_score = cross_val_score(model, iris_X, iris_y, cv=10)
print "Cross Validation Scores"
print cross_score
print "mean:",np.mean(cross_score)

import coremltools
# convert to coreml model
coreml_model = coremltools.converters.sklearn.convert(model, iris.feature_names, "class")

# set parameters of the model
coreml_model.short_description = "Iris dataset classification model"
coreml_model.output_description["class"] = "The species of flower"

# Save the model
coreml_model.save("../ios/IrisTest/Model/iris_logistic_regression.mlmodel")

Data For Testing:
[[6.7 3.  5.2 2.3]
 [4.9 3.1 1.5 0.1]
 [7.7 2.6 6.9 2.3]
 [6.2 3.4 5.4 2.3]
 [5.  3.5 1.3 0.3]
 [6.  3.4 4.5 1.6]
 [6.9 3.1 5.1 2.3]
 [7.2 3.6 6.1 2.5]
 [7.9 3.8 6.4 2. ]
 [6.  2.2 4.  1. ]]
[2 0 2 2 0 1 2 2 2 1]
Cross Validation Scores
[0.93333333 0.93333333 1.         1.         1.         0.85714286
 0.92857143 1.         0.91666667 1.        ]
mean: 0.9569047619047618


In [2]:
!ls ../ios/IrisTest/Model

README.ml                        iris_logistic_regression.mlmodel
