### Trying to convert a simple model

In [5]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

# load iris dataset and set features / target.
iris = datasets.load_iris()
indices = np.random.permutation(len(iris.data))
iris_X = iris.data[indices[:-10]]
iris_y = iris.target[indices[:-10]]

print("Data For Testing:")
print(iris.data[indices[-10:]])
print(iris.target[indices[-10:]])

# Create and fit a model
model = LogisticRegression()
model.fit(iris_X, iris_y)
cross_score = cross_val_score(model, iris_X, iris_y, cv=10)
print "Cross Validation Scores"
print cross_score
print "mean:",np.mean(cross_score)

import coremltools
# convert to coreml model
coreml_model = coremltools.converters.sklearn.convert(model, iris.feature_names, "class")

# set parameters of the model
coreml_model.short_description = "Iris dataset classification model"
coreml_model.output_description["class"] = "The species of flower"

# Save the model
coreml_model.save("../model/iris_logistic_regression.mlmodel")

Data For Testing:
[[6.2 2.2 4.5 1.5]
 [5.3 3.7 1.5 0.2]
 [4.9 3.1 1.5 0.1]
 [5.5 2.5 4.  1.3]
 [6.1 2.8 4.7 1.2]
 [6.3 2.8 5.1 1.5]
 [6.4 2.8 5.6 2.2]
 [5.2 3.5 1.5 0.2]
 [6.  2.7 5.1 1.6]
 [5.7 2.8 4.1 1.3]]
[1 0 0 1 1 2 2 0 1 1]
Cross Validation Scores
[1.         0.8        0.93333333 0.93333333 0.86666667 1.
 1.         1.         1.         1.        ]
mean: 0.9533333333333334


In [7]:
!ls ../model

iris_logistic_regression.mlmodel
