### Trying to convert a simple model

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

# load iris dataset and set features / target.
iris = datasets.load_iris()
indices = np.random.permutation(len(iris.data))
iris_X = iris.data[indices[:-10]]
iris_y = iris.target[indices[:-10]]

print("Data For Testing:")
print(iris.data[indices[-10:]])
print(iris.target[indices[-10:]])

# Create and fit a model
model = LogisticRegression()
model.fit(iris_X, iris_y)
cross_score = cross_val_score(model, iris_X, iris_y, cv=10)
print "Cross Validation Scores"
print cross_score
print "mean:",np.mean(cross_score)

import coremltools
# convert to coreml model
coreml_model = coremltools.converters.sklearn.convert(model, iris.feature_names, "class")

# set parameters of the model
coreml_model.short_description = "Iris dataset classification model"
coreml_model.output_description["class"] = "The species of flower"

# Save the model
coreml_model.save("../ios/IrisTest/Model/iris_logistic_regression.mlmodel")

Data For Testing:
[[ 6.6  2.9  4.6  1.3]
 [ 5.4  3.   4.5  1.5]
 [ 6.2  3.4  5.4  2.3]
 [ 5.8  2.6  4.   1.2]
 [ 5.   3.5  1.3  0.3]
 [ 6.2  2.9  4.3  1.3]
 [ 5.1  3.5  1.4  0.2]
 [ 6.   2.2  5.   1.5]
 [ 5.1  3.3  1.7  0.5]
 [ 5.   3.   1.6  0.2]]
[1 1 2 1 0 1 0 2 0 0]
Cross Validation Scores
[ 1.          0.93333333  1.          1.          0.86666667  0.93333333
  1.          1.          0.91666667  1.        ]
mean: 0.965


In [2]:
!ls ../ios/IrisTest/Model

iris_logistic_regression.mlmodel  README.md
